import localFont from "next/font/local";
import "../globals.css";
import DesktopNavigation from "@/components/DesktopNavigation"
import ChatList from "@/components/ChatList"
import BottomNavigation from "@/components/BottomNavigation"
import { Suspense } from "react";
import { SocketProvider } from "@/socketProvider/SocketProvider";
import Dialog from "@/components/Dialog";




export const metadata = {
  title: "tamjid",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
      <SocketProvider>
        <Dialog/>
          <Suspense fallback={<div>Loading...</div>}>
            {children}
          </Suspense>
        

      </SocketProvider>


    </div>

    //     <div
    //       className={` antialiased`}
    //     >
    //  <div className="grid grid-rows-[10%_80%_10%] lg:grid-rows-none lg:grid-cols-[10%_30%_60%] xl:grid-cols-[5%_25%_70%] h-screen">
    //   <div className="bg-blue-300 flex items-center justify-center lg:hidden">Top (25)</div>


    // <div className="bg-blue-300 hidden lg:flex flex-col justify-evenly ">
    //     <DesktopNavigation />
    // </div>


    // <div className="bg-green-300 flex items-center justify-center">
    //     <ChatList />

    //  </div>


    //   <div className="bg-red-600 items-center justify-center hidden lg:flex ">
    //  desktop inbox
    //  {/* <Inbox /> */}
    //  {children}

    //   </div>



    //   <div className="bg-red-300 flex items-center lg:hidden ">
    //       <BottomNavigation />
    //   </div>
    //   </div> 
    //     </div>

  );
}
