import localFont from "next/font/local";
import "../../../globals.css";
import DesktopNavigation from "@/components/DesktopNavigation"
import ChatList from "@/components/ChatList"
import BottomNavigation from "@/components/BottomNavigation"


export const metadata = {
  title: "dynamic inbox",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (

    <div>
        {children}
    </div>


  //   <div>
  //     <div
  //       className={` antialiased hidden lg:block`}
  //     >
  //  <div className="grid grid-rows-[10%_80%_10%] lg:grid-rows-none lg:grid-cols-[10%_30%_60%] xl:grid-cols-[5%_25%_70%] h-screen">
  //   <div className=" flex items-center justify-center lg:hidden">Top (25)</div>


  // <div className="border-r border-black hidden lg:flex flex-col justify-evenly ">
  //     <DesktopNavigation />
  // </div>


  // <div className="bg-gray-100 border-r border-black px-4 overflow-y-auto ">
  //     <ChatList />

  //  </div>


  //   <div className="  items-center justify-center hidden lg:block ">
  //  {/* <Inbox /> */}
  //  {children}

  //   </div>



  //   <div className="bg-red-300 flex items-center lg:hidden ">
  //       <BottomNavigation />
  //   </div>
  //   </div> 
  //     </div>



  //    <div className=" lg:hidden">
  //    {children}
  //    </div>


  //   </div>

  

   
  );
}
